name: Unzip Project

on:
  push:
    paths:
      - "bharath-portfolio-modes-avatar.zip"   # change to your zip filename

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip uploaded file
        run: |
          sudo apt-get install unzip -y
          unzip -o project.zip -d extracted
          rm project.zip
          cp -r extracted/* .
          rm -rf extracted

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzipped project"
          git push
